# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(400, 483)
        self.verticalLayout = QtWidgets.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.versionLabel = QtWidgets.QLabel(About)
        self.versionLabel.setText("")
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout.addWidget(self.versionLabel)
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(About)
        self.label_5.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label = QtWidgets.QLabel(About)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.AboutTextBrowser = QtWidgets.QTextBrowser(About)
        self.AboutTextBrowser.setOpenExternalLinks(True)
        self.AboutTextBrowser.setObjectName("AboutTextBrowser")
        self.verticalLayout.addWidget(self.AboutTextBrowser)
        self.buttonBox = QtWidgets.QDialogButtonBox(About)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(About)
        self.buttonBox.accepted.connect(About.accept) # type: ignore
        self.buttonBox.rejected.connect(About.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label_3.setText(_translate("About", "# Drop analysis"))
        self.label_2.setText(_translate("About", "This software is made by Mathijs van Gorcum and released under [GPLv3](https://codeberg.org/mvgorcum/Sessile.drop.analysis/src/branch/master/LICENSE)."))
        self.label_4.setText(_translate("About", "Homepage: [drop-analysis.com](https://drop-analysis.com)"))
        self.label_5.setText(_translate("About", "Source code: [codeberg.org/mvgorcum/sessile.drop.analysis](https://codeberg.org/mvgorcum/Sessile.drop.analysis)"))
        self.label.setText(_translate("About", "The following open source packages are used:"))
        self.AboutTextBrowser.setHtml(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://numpy.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">numpy</span></a> [BSD 3-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://pandas.pydata.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">pandas</span></a> [BSD 3-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://scipy.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">scipy</span></a> [BSD 3-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.riverbankcomputing.com/software/pyqt/\"><span style=\" text-decoration: underline; color:#2980b9;\">pyqt5</span></a> [GPL v3]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://opencv.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">opencv</span></a> [apache]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://openpyxl.readthedocs.io/\"><span style=\" text-decoration: underline; color:#2980b9;\">openpyxl</span></a> [MIT]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/astrofrog/fast-histogram\"><span style=\" text-decoration: underline; color:#2980b9;\">fast-histogram</span></a> [BSD 2-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/bdhammel/least-squares-ellipse-fitting\"><span style=\" text-decoration: underline; color:#2980b9;\">lsq-ellipse</span></a> [MIT]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/imageio/imageio\"><span style=\" text-decoration: underline; color:#2980b9;\">imageio</span></a> [BSD 2-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://shapely.readthedocs.io/en/stable/manual.html\"><span style=\" text-decoration: underline; color:#2980b9;\">shapely</span></a> [BSD 3-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.pyqtgraph.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">pyqtgraph</span></a> [MIT]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/uiri/toml\"><span style=\" text-decoration: underline; color:#2980b9;\">toml</span></a> [MIT]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.h5py.org/\"><span style=\" text-decoration: underline; color:#2980b9;\">h5py</span></a> [BSD 3-clause]</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/ActiveState/appdirs\"><span style=\" text-decoration: underline; color:#2980b9;\">appdirs</span></a> [MIT]</p></body></html>"))
